# Generated by Django 5.2.6 on 2025-09-29 15:03

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_portal_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessassignment',
            options={'ordering': ('-active', 'portal', 'role'), 'permissions': [('can_push_vendor', 'Can push to vendor'), ('can_sync_vendor', 'Can sync from vendor')]},
        ),
        migrations.RemoveConstraint(
            model_name='portal',
            name='netbox_portal_access_portal_unique_vendor_portal',
        ),
        migrations.RemoveConstraint(
            model_name='vendorrole',
            name='netbox_portal_access_vendorrole_unique_portal_role',
        ),
        migrations.RenameIndex(
            model_name='accessassignment',
            new_name='netbox_port_active_4087bd_idx',
            old_name='netbox_port_active__be8f9f_idx',
        ),
        migrations.AddField(
            model_name='accessassignment',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessassignment',
            name='last_push_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessassignment',
            name='last_push_status',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accessassignment',
            name='remote_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='adapter',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='request_retries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='portal',
            name='request_timeout',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='portal',
            name='ssl_verify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessassignment',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='accessassignment',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='portal',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='vendorrole',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='vendorrole',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='portal',
            unique_together={('vendor_ct', 'vendor_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorrole',
            unique_together={('portal', 'name')},
        ),
]
