# Generated by Django 5.2.6 on 2025-09-29 20:03

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_portal_access', '0002_alter_accessassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('data_encrypted', models.TextField()),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True, null=True)),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='netbox_portal_access.portal')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-last_updated',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
